name: PHP

on:
  pull_request: { }
  push:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  php-library:
    uses: equisoft-actions/php-workflows/.github/workflows/php-library.yml@v7
    secrets: inherit
    with:
      checks: phpcs,phpunit,psalm
      php-version: '8.1'
      extensions: pcov
